### ISSUE TITLE
Why is there no activation function between convolutional layers ? 

### ISSUE THREAD

**Issue by hugovergnes** [YuGuangWang/PAN#1]
Hello, 

That's a great paper & code!

But I wonder why there is no activation function between each layers ? I mean after each PANConv ? 

Thanks :)

**Comment by YuGuangWang** [comment]
Thanks.
We did not use activation for graph convolution for PANConv,  nor we used activation for the baselines (GCN, GIN etc.) on benchmark graph datasets.
The activativation functions such as ReLU can be added to futhure enhance the performance. The impact of activation function can be seen in e.g. 
https://arxiv.org/pdf/1906.02174.pdf 

Best,
Yuguang
