### ISSUE TITLE
Gap?

### ISSUE THREAD

**Issue by xnuohz** [YuGuangWang/PAN#3]
Hi,
I tried to run your code on PROTEINS, PROTEINS_full and NCI1, and it seems that there exists gap between the result and the paper?

| | PROTEINS | PROTEINS_full | NCI1 |
| :-: | :-: | :-: | :-: |
| PANConv+PANPool(paper, table 5) | 76.6 | 71.7 | 60.8 |
| run code | 71.4 | 67.5 | 53.7 |

**Comment by YuGuangWang** [comment]
Thanks for the message.

The results are achievable with a proper choice of hyperparameters:

*PROTEINS: 0.7670+0.0305
python pan_benchmark.py --dataset_name PROTEINS --L 3 --runs 10 --batch_size 32 --learning_rate 0.001 --weight_decay 5e-4 --pool_ratio 0.3 --nhid 512 --epochs 50

*PROTEINS_full:  0.7009+0.0377
python pan_benchmark.py --dataset_name PROTEINS_full --L 1 --runs 10 --batch_size 128 --learning_rate 0.001 --weight_decay 5e-4 --pool_ratio 0.5 --nhid 512 --epochs 50

*NCI1: 0.6027+0.0113
python pan_benchmark.py --dataset_name NCI1 --L 3 --runs 10 --batch_size 256 --learning_rate 0.001 --weight_decay 5e-4 --pool_ratio 0.5 --nhid 512 --epochs 100

All the experiments were run on a server with Intel(R) Core(TM) i9-9820X CPU 3.30GHz, NVIDIA TITAN V GV100.

Hope it helps.
Best,
Yuguang

**Comment by xnuohz** [comment]
Ok, I'll try it later.

**Comment by xnuohz** [comment]
I used your hyperparameters to run on PROTEINS, and the mean test acc is 0.7036 over 10 times, the best can be up to 0.74. It is wired.

**Comment by YuGuangWang** [comment]
Yes, that's wired. What about the other two datasets (PROTEINS_full, NCI1)?

**Comment by YuGuangWang** [comment]
My colleague Dr Junyu Xuan will contact you by email (xnuohz@126.com) and send our running package (including datasets) and running environment.
