### ISSUE TITLE
mkl-fft version

### ISSUE THREAD

**Issue by lingjiekong** [YuGuangWang/PAN#4]
It looks like mkl-fft does not have version mkl-fft==1.0.15 as requirements.txt specified. It looks all available version are here: https://pypi.org/project/mkl-fft/#history

**Comment by YuGuangWang** [comment]
You can use any version > 1.0.6.
Thanks!

**Comment by YuGuangWang** [comment]
Maybe better to use the latest version 1.3.0.

**Comment by lingjiekong** [comment]
thank you!
