### ISSUE TITLE
Index Error for OGB dataset

### ISSUE THREAD

**Issue by lingjiekong** [YuGuangWang/PAN#5]
I made some modification to load in the OGB ogbg-mol dataset https://ogb.stanford.edu/docs/graphprop/#ogbg-mol.

It runs fine initially for couple hours and eventually crashed with the following error. I am just curious whether such error has been seen on any other large dataset. If so, what is the suggestion on how to mitigate it.

  File "pan_benchmark.py", line 257, in filter_adj
    row, col = mask[row], mask[col]
IndexError: index -5324638546475089920 is out of bounds for dimension 0 with size 8117

Thanks ahead!

**Comment by YuGuangWang** [comment]
Thanks for pointing this out.
We have not tried `ogbg-molhiv` yet. The graphs of this dataset are not large. With a reasonable batch size, e.g. 256, the running of PAN should be OK. But maybe the training will be a bit slow.
What --L did you use? When L is high, e.g. >5, the computational cost will increase, and training speed will be reduced.
Also, we have another version of PAN with sparse tensor operations. It may help with large-scale datasets training. I can send that version to you if you need it.

Best regards,
Yu Guang

**Comment by YuGuangWang** [comment]
Also, can you check the property of the graph that returns this error; for example, does the graph have isolated nodes? This may be a potential bug for PAN.

**Comment by lingjiekong** [comment]
Thanks for the quick follow up. Below is how I ran your code.

```python pan_benchmark.py --L 3 --runs 2 --batch_size 320 --learning_rate 0.005 ```

I used a fairly shallow order L, with L = 3, batch_size = 320, and learning_rate = 0.005. 

It looks like the size of `ogbg-molhiv` is `41127` and our training crashed due the the index issue I posted above at epoch 49. Therefore, it is roughly at graph (49 * 320 = ~ 15680). I will do a some more data preprocessing to filter out graph with single isolated nodes as well as two points only to see whether this issue can be mitigated and keep you posted here.

Meanwhile, if you can share with me the version of PAN with sparse tensor operation, it will be great.

One more quick question here. It looks like the PAN here is for heterogeneous graph with same edges features. Have you think about expand PAN for heterogeneous graph with different edge features.

**Comment by lingjiekong** [comment]
I made a bit further modification on the code to see which graph in the `ogbg-molhiv` dataset that cause the crash. Below all my modifications.

- load all data into the trainer dataloader without shuffle, so I can point out which graph has an issue
- use batch size of 1, so either for me to find graph has an issue

However, it looks like specific graph that cause a crash in one sweep through each dataset cannot be reproduced.

For example, in one run through all training data with batch size 1, graph 7680 with 31 nodes cause a crash as below.
![fail_graph_1](https://user-images.githubusercontent.com/19255182/110984052-7419ba00-831f-11eb-9de3-7dbae0cca0ae.png)
```
[train data]: graph id 7680, num node 31
Traceback (most recent call last):
  File "pan_benchmark.py", line 904, in <module>
    output, _ = model(data)
  File "//anaconda3/envs/cs224w/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pan_benchmark.py", line 713, in forward
    x, edge_index, _, batch, perm, score_perm = self.pool2(x, edge_index, batch=batch, M=M)
  File "//anaconda3/envs/cs224w/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pan_benchmark.py", line 209, in forward
    edge_index, edge_weight = self.filter_adj(edge_index, edge_weight, perm, num_nodes=score.size(0))
  File "pan_benchmark.py", line 261, in filter_adj
    row, col = mask[row], mask[col]
IndexError: index 17 is out of bounds for dimension 0 with size 16
```

while in another run, graph 1724 with 20 nodes cause a different crash as below which do not crash in the first time.
![fail_graph_2](https://user-images.githubusercontent.com/19255182/110984060-77ad4100-831f-11eb-95a0-6bf78e612637.png)
```
[train data]: graph id 1724 num node 20
Traceback (most recent call last):
  File "pan_benchmark.py", line 904, in <module>
    output, _ = model(data)
  File "//anaconda3/envs/cs224w/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pan_benchmark.py", line 719, in forward
    x, edge_index, _, batch, perm, score_perm = self.pool3(x, edge_index, batch=batch, M=M)
  File "//anaconda3/envs/cs224w/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pan_benchmark.py", line 209, in forward
    edge_index, edge_weight = self.filter_adj(edge_index, edge_weight, perm, num_nodes=score.size(0))
  File "pan_benchmark.py", line 261, in filter_adj
    row, col = mask[row], mask[col]
IndexError: index 6 is out of bounds for dimension 0 with size 5
```

Also, both graphs have neither isolated nodes or only two nodes. However, the strange thing is that the mask dimension is wrong, if I understand it correctly, its dimension should be the same size of number of nodes.

Thanks ahead for the help!

**Comment by YuGuangWang** [comment]
Thanks for the test and updates for the codes.
Yes, happy to accept your pull request.

It is OK to ignore the edge features. A simple way to include more edge features is to turn the edge feature vector to a scalar, for example, by taking the mean of edge features, or other statistical methods. To solve it fundamentally, we may need to change quite a few codes for embedding edge feature vectors with different length to the entries of the adjacency matrix A when computing the max-entropy matrix (MET).
 
Best,
Yuguang

**Comment by YuGuangWang** [comment]
If you are interested, we can work on the extension of PAN to the edge feature with varying dimension?
Best,
Yuguang

**Comment by lingjiekong** [comment]
After a bit more investigation, I think I might figure out the root cause.

I was initially use a `cpu` instance with `torch==1.4.0` with the index error as above.

After I provision an ec2 gpu instance, it looks like the issue is gone. However, under the condition that aws ec2 instance is using cuda 11.0, I have to bump up the torch version to 1.7.0 and other torch dependencies `https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`.

Let me give the average of edge features a try first and I would like to work on the extension of PAN.

Best,

-Lingjie
